# Generated by Django 6.0 on 2026-01-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_video', '0002_category_group_remove_users_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
    ]
