# Generated by Django 6.0 on 2026-01-04 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_video', '0004_remove_course_teacher_course_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Users',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'teacher'}, to=settings.AUTH_USER_MODEL),
        ),
    ]
