# Generated by Django 6.0 on 2026-01-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_video', '0005_remove_course_users_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
