# Generated by Django 6.0 on 2026-01-04 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_video', '0006_alter_course_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoprogress',
            old_name='Section',
            new_name='video',
        ),
        migrations.AddField(
            model_name='vazifa_bajarish',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'teacher'}, related_name='teaching_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='small_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='videoprogress',
            unique_together={('user', 'video')},
        ),
    ]
