# Generated by Django 6.0 on 2026-01-05 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_video', '0007_rename_section_videoprogress_video_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionprogress',
            old_name='Section',
            new_name='section',
        ),
    ]
