# Generated by Django 6.0 on 2026-01-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_video', '0008_rename_section_sectionprogress_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionprogress',
            name='score_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vazifa_bajarish',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vazifa_bajarish',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='vazifalar/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_blocked',
            field=models.BooleanField(default=True),
        ),
    ]
