# Generated by Django 6.0 on 2026-01-16 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_video', '0009_sectionprogress_score_percent_vazifa_bajarish_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vazifa_bajarish',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vazifalar', to='main_video.section'),
            preserve_default=False,
        ),
    ]
