# Generated by Django 6.0 on 2026-01-16 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_video', '0011_alter_vazifa_bajarish_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vazifa_bajarish',
            name='section',
        ),
    ]
