# Generated by Django 6.0 on 2026-01-16 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_video', '0012_remove_vazifa_bajarish_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='vazifa_bajarish',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vazifalar', to='main_video.section'),
        ),
    ]
