# Generated by Django 6.0 on 2026-01-16 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_video', '0013_vazifa_bajarish_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vazifa_bajarish',
            name='section',
        ),
        migrations.AlterField(
            model_name='missiya',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missiyas', to='main_video.section'),
        ),
        migrations.AlterField(
            model_name='vazifa_bajarish',
            name='missiya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vazifalar', to='main_video.missiya'),
        ),
    ]
